### PR TITLE
Switch to IPFS for content distribution

### PR DESCRIPTION
**Pull request by ghost**
Switch to IPFS for content distribution.

Replaces WebTorrent with IPFS.
Publish, fetch, and tile transfer tested successfully on an isolated testnet.

Does not include a switch to suitable new network. Requires a new chain and a compatible genesis block. The relevant change is the `content` field of an output, previously a 32-byte torrent hash, is now a 34-byte IPFS hash.

Lowers memory usage of the node. Reduces errors in node output.

Primary work by @HPrivakos. Contributions, pointers, testing, and discussion from @thoragio, @eordano, and @Alonzo-Coeus.

### CODE REVIEW

**Comment by ghost** [comment]
IPFS currently doesn't work on Windows, so this change breaks the node on Windows.

**Comment by HPrivakos** [comment]
A bit more information:
- The node can now instant shutdown
- The 34-bytes length hash is when converted to hex (Torrents hash are already hex, but IPFS hash are base58)

**Comment by kylerchin** [comment]
:+1: 
Awesome!
(hopefully we can get it working in windows, cuz old people have to use it.)

**Comment by ghost** [comment]
Noticed a problem with establishing the current content for a tile after content acquisition. Just pushed a fix for that.

**Comment by ghost** [comment]
This possibly resolves or obviates these issues:
* #58 Repeated WebTorrent verification failures
* #57 Assertion failures prevent reorganizing chain
* #45 Repeated assertion failures
* #42 Error when creating RTCPeerConection: the electron-webrtc daemon has been closed
* #28 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
* #19 node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
* #17 Possible memory leak / OOM issue
* #6 add rpc calls to see webtorrent status
* #3 Optimize memory usage
* #2 Some webtorrent connections hang the node with EPIPE

Not sure why, but also stopped seeing these issues. Possibly resolves them for some unclear reason:
* #71 Consistent `Number exceeds 2^53-1` errors on Windows
* #26 [error] Number exceeds 2^53-1

**Comment by eordano** [comment]
@martriay can we please merge this??

**Comment by martriay** [comment]
This work is continued in #81

**Pull request closed without merging**
