### PR TITLE
Expose port 5000 from docker environment

### PR DESCRIPTION
**Pull request by cougarbytes**
Expose port 5000 from docker environment in order to allow users to access web dashboard remotely.

### CODE REVIEW

**Comment by martriay** [comment]
Awesome! The port is still missing in the `docker-compose.yml` file, I'll add it.

**Comment by cougarbytes** [comment]
I was about to do another reuqest on that

**Comment by martriay** [comment]
@CJHackerz sry, already pushed it 😊

**Comment by cougarbytes** [comment]
I am not coding pro but, This is my first open source contribution ever 😄

**Comment by ghost** [comment]
Well done friend. Good change. :1st_place_medal:

**Comment by martriay** [comment]
@CJHackerz congratulations! Now you're a Decentraland contributor. Go for it!

**Comment by cougarbytes** [comment]
Thank you! Gonna celebrate this contribution with a beer cheers! 😸

**Pull request merged**
