### PR TITLE
Update listmine.js

### PR DESCRIPTION
**Pull request by HPrivakos**
Use dumpblockchain command

### CODE REVIEW

**Comment by maraoz** [comment]
What does this change do?

**Comment by HPrivakos** [comment]
It's a update of a script from @eordano.
His script was making a lot of rpc call for check lands with content, i added the support of dumpblockchain for avoid all these rpc command

**Comment by maraoz** [comment]
@eordano can you review?

**Comment by eordano** [comment]
Can't merge independently of using IPFS :( I'll reopen if code to switch to it is removed.

Thanks @HPrivakos!

**Pull request closed without merging**
